name: Pyinstaller Build

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7 #use older python version so that
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install -y make gcc libgtk-3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libgstreamer-gl1.0-0 freeglut3 freeglut3-dev python-gst-1.0 python3-gst-1.0 libglib2.0-dev ubuntu-restricted-extras libgstreamer-plugins-base1.0-dev
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build For Linux
      run: |
        pyinstaller --onefile avw-calc.py -n avw-calc-gui-linux
    - name: Archive Pyinstaller File
      uses: actions/upload-artifact@v2
      with:
        name: avw-calc-gui-linux
        path: dist/avw-calc-gui-linux
